name: world_riichi
description: "World Riichi"

# prevent the package from being accidentally published to pub.dev
publish_to: 'none'

# A version number is build name: three numbers separated by dots, like 1.2.43
# then a + , then the build number

# IMPORTANT: the build number must be increased each time it is uploaded to the Play Store

# In iOS, build name is used as CFBundleShortVersionString
# build number is used as CFBundleVersion.

version: 1.0.8+56

environment:
  sdk: '>=3.2.5 <4.0.0'

# To automatically upgrade dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`

dependencies:
  flutter:
    sdk: flutter

  alarm: ^5.0.2
  cached_network_image: ^3.4.1
  cloud_firestore: ^5.6.5
  collection: ^1.19.1
  data_table_2: ^2.5.18
  equatable: ^2.0.7
  firebase_app_installations: ^0.3.2+4
  firebase_core: ^3.12.1
  firebase_messaging: ^15.2.4
  flutter_autostart: ^0.0.2
  flutter_fgbg: any # used directly and by alarm too
  flutter_html: ^3.0.0
  flutter_riverpod: ^2.6.1
  flutter_sticky_header: ^0.7.0
  flutter_timezone: ^4.1.0
  flutter_typeahead: ^5.2.0
  http: ^1.3.0
  intl: ^0.20.2
  permission_handler: ^11.4.0
  restart_app: ^1.3.2
  shared_preferences: ^2.5.2
  syncfusion_flutter_charts: ^28.2.7
  timezone: ^0.10.0
  url_launcher: ^6.3.1


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.14.3
  flutter_lints: ^5.0.0

# dart run flutter_launcher_icons
flutter_launcher_icons:
  android: "ic_launcher"
  image_path_android: assets/icon/android1024.png
  min_sdk_android: 21
  ios: true
  image_path_ios: assets/icon/apple512.png
  remove_alpha_ios: true
  windows:
    generate: false
  macos:
    generate: false
  web:
    generate: false

# The following section is specific to Flutter packages
flutter:
  # needed for the Icons class
  uses-material-design: true

  assets:
    - assets/audio/notif.mp3
