name: aim_tournaments
description: "All-Ireland Mahjong (superseded by the World Riichi App)"

# prevent the package from being accidentally published to pub.dev
publish_to: 'none'

version: 1.0.2+44

environment:
  sdk: '>=3.2.5 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  url_launcher: ^6.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.14.2
  flutter_lints: ^5.0.0

# flutter pub run flutter_launcher_icons
flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon/icon.png"
  min_sdk_android: 21 # android min sdk min:16, default 21

# The following section is specific to Flutter packages
flutter:
  # needed for the Icons class
  uses-material-design: true
