name: aim_tournaments
description: "All-Ireland Mahjong"

# prevent the package from being accidentally published to pub.dev
publish_to: 'none'

# A version number is build name: three numbers separated by dots, like 1.2.43
# then a + , then the build number

# IMPORTANT: the build number must be increased each time it is uploaded to the Play Store

# In iOS, build name is used as CFBundleShortVersionString
# build number is used as CFBundleVersion.

version: 1.0.0+42

environment:
  sdk: '>=3.2.5 <4.0.0'

# To automatically upgrade dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`

dependencies:
  flutter:
    sdk: flutter

  alarm: ^3.1.3
  cached_network_image: ^3.3.1
  cloud_firestore: ^5.0.0
  collection: ^1.18.0
  data_table_2: ^2.5.12
  equatable: ^2.0.5
  firebase_core: ^3.0.0
  firebase_messaging: ^15.0.0
  flutter_autostart: ^0.0.2
  flutter_html: ^3.0.0-beta.2
  flutter_riverpod: ^2.5.1
  flutter_sticky_header: ^0.6.5
  flutter_timezone: ^3.0.0
  flutter_typeahead: ^5.2.0
  intl: ^0.18.0
  permission_handler: ^11.3.1
  shared_preferences: ^2.0.0
  syncfusion_flutter_charts: ^27.1.48 # 22.2.12 # HACK Downgraded due to #1907
  timezone: ^0.9.3
  url_launcher: ^6.2.6


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.13.1
  flutter_lints: ^4.0.0

# flutter pub run flutter_launcher_icons
flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon/icon.png"
  min_sdk_android: 21 # android min sdk min:16, default 21

# The following section is specific to Flutter packages
flutter:
  # needed for the Icons class
  uses-material-design: true

  assets:
    - assets/audio/notif.mp3
