name: aim_tournaments
description: "All-Ireland Mahjong"

# prevent the package from being accidentally published to pub.dev
publish_to: 'none'

# A version number is build name: three numbers separated by dots, like 1.2.43
# then a + , then the build number

# IMPORTANT: the build number must be increased each time it is uploaded to the Play Store

# In iOS, build name is used as CFBundleShortVersionString
# build number is used as CFBundleVersion.

version: 0.2.1+19

environment:
  sdk: '>=3.2.5 <4.0.0'

# To automatically upgrade dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`

dependencies:
  flutter:
    sdk: flutter

  alarm: ^3.1.3
  cloud_firestore: ^4.15.9
  firebase_core: any
  firebase_messaging: ^14.0.0
  flutter_autostart: ^0.0.2
  flutter_local_notifications: ^17.1.2
  flutter_redux: ^0.10.0
  flutter_timezone: ^1.0.8
  flutter_typeahead: ^5.2.0
  intl: ^0.19.0
  permission_handler: ^11.3.1
  redux: any
  shared_preferences: ^2.0.0
  timezone: ^0.9.3
  url_launcher: ^6.2.6

  # add Apple Cupertino Icons font:
  # cupertino_icons: ^1.0.2


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

  flutter_launcher_icons: ^0.13.1

# flutter pub run flutter_launcher_icons
flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon/icon.png"
  min_sdk_android: 21 # android min sdk min:16, default 21

# The following section is specific to Flutter packages
flutter:

  # needed for the Icons class
  uses-material-design: true

  assets:
    - assets/audio/notif.mp3
