"""empty message

Revision ID: fefaec5da36b
Revises: 
Create Date: 2024-04-07 18:46:45.010594

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fefaec5da36b'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tournament',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user',
    sa.Column('email', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('email')
    )
    op.create_table('access',
    sa.Column('user_email', sa.String(), nullable=False),
    sa.Column('tournament_id', sa.String(), nullable=False),
    sa.Column('role', sa.Enum('admin', 'editor', name='roles', create_constraint=True), nullable=False),
    sa.ForeignKeyConstraint(['tournament_id'], ['tournament.id'], ),
    sa.ForeignKeyConstraint(['user_email'], ['user.email'], ),
    sa.PrimaryKeyConstraint('user_email', 'tournament_id')
    )
    # ### end Alembic commands ###

    user = sa.table('user', sa.column('email', sa.String()))
    op.bulk_insert(user, [
        {'email': 'mj.apply.sci@gmail.com'},
        {'email': 'andrew.smith.gibbs@gmail.com'},
        ])


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('access')
    op.drop_table('user')
    op.drop_table('tournament')
    # ### end Alembic commands ###
